# Generated by Django 4.0.1 on 2022-01-20 05:46

from django.db import migrations


class Migration(migrations.Migration):
    def add_categories(apps, schema_editor):
        Category = apps.get_model('store', 'Category')

        categories = [
            ['Seeds', 'sesame'],
            ['Fertilizer', 'fertilizer-bag'],
            ['Machinary', 'farm-tractor'],
            ['Terrace Farming', 'seedling'],
            ['Cerals', 'grain'],
            ['Vegetables', 'asparagus'],
            ['Fruits & Nuts', 'grapes'],
            ['Crops', 'plant-seed'],
            ['Livestock', 'cow'],
            ['Others', 'watering-can'],
        ]

        for category in categories:
            new_category = Category(name=category[0], icon=category[1])
            new_category.save()

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
