# Generated by Django 4.0.1 on 2022-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carousel_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(max_length=500, upload_to='static'),
        ),
    ]
