# Generated by Django 4.0.1 on 2022-01-22 13:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='jpt/haha'), upload_to=''),
        ),
    ]
